# Generated by Django 3.0.2 on 2020-01-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chakras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(max_length=20)),
                ('sanskrit_name', models.CharField(max_length=20)),
                ('number', models.IntegerField()),
                ('color', models.CharField(max_length=10)),
                ('note', models.CharField(max_length=8)),
                ('base_frequency', models.IntegerField()),
                ('octave_half', models.IntegerField()),
                ('octave_qtr', models.IntegerField()),
                ('description', models.TextField()),
                ('sound', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(max_length=30)),
                ('primary_chakra', models.IntegerField()),
                ('secondary_chakra', models.IntegerField(null=True)),
                ('tertiary_chakra', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('home_chakra_number', models.IntegerField(null=True)),
                ('home_note', models.CharField(max_length=2, null=True)),
                ('home_frequency', models.IntegerField(null=True)),
            ],
        ),
    ]
