# Generated by Django 2.0.5 on 2018-05-03 00:13

from django.db import migrations


def seed(apps, schema_editor):
    Chakras = apps.get_model('chakra_healer', 'Chakras')
    Conditions = apps.get_model('chakra_healer', 'Conditions')
    
    # Chakras
    chakra1 = Chakras(english_name = 'Root', number = 1, sanskrit_name = 'Mulhadhara', color = 'Red',  note = 'A', sound = 'Ay Way', base_frequency = 432, octave_half = 216, octave_qtr = 108, description = 'The Root chakra represents grounding')
    chakra1.save()

    chakra2 = Chakras(english_name = 'Sacral', number = 2, sanskrit_name = 'Swadhistana', color = 'Orange',  note = 'B', sound = 'Ee Me', base_frequency = 480, octave_half = 240, octave_qtr = 120, description = 'The Sacral Chakra represents connection.')
    chakra2.save()

    chakra3 = Chakras(english_name = 'Solar Plexus', number = 3, sanskrit_name = 'Manipura', color = 'Yellow',  note = 'C', sound = 'Uuh Cup', base_frequency = 528, octave_half = 264, octave_qtr = 132, description = 'The Solar Plexus Chakra represents power.')
    chakra3.save()

    chakra4 = Chakras(english_name = 'Heart', number = 4, sanskrit_name = 'Anahata', color = 'Green',  note = 'D', sound = 'Eu You', base_frequency = 600, octave_half = 300, octave_qtr = 150, description = 'The Heart Chakra represents Union.')
    chakra4.save()

    chakra5 = Chakras(english_name = 'Throat', number = 5, sanskrit_name = 'Vishuddha', color = 'Blue',  note = 'E', sound = 'Oh Go', base_frequency = 672, octave_half = 336, octave_qtr = 168, description = 'The Throat Chakra respresents identity and voice.')
    chakra5.save()

    chakra6 = Chakras(english_name = 'Third Eye', number = 6, sanskrit_name = 'Ajna', color = 'Indigo',  note = 'F', sound = 'Ah Mah', base_frequency = 720, octave_half = 360, octave_qtr = 180, description = 'The Third Eye represents timeless vision.')
    chakra6.save()

    chakra7 = Chakras(english_name = 'Crown', number = 7, sanskrit_name = 'Sahasrara', color = 'Violet',  note = 'G', sound = 'I My', base_frequency = 768, octave_half = 384, octave_qtr = 192, description = 'The Crown Chakra represents divine oneness.')
    chakra7.save()
    
    # Conditions

    Condition(
        name = 
    )
    Student(name = "Harry Potter", image_url = "http://images1.wikia.nocookie.net/__cb20111110202524/harrypotter/images/thumb/d/d4/Dhharryroomhighreso.jpg/250px-Dhharryroomhighreso.jpg", house = gryffindor).save()
    

    Student(name = "Draco Malfoy", image_url = "http://images1.wikia.nocookie.net/__cb20100925140918/harrypotter/images/thumb/2/21/Dracodh.jpg/250px-Dracodh.jpg", house = slytherin).save()
    Student(name = "Pansy Parkinson", image_url = "http://images1.wikia.nocookie.net/__cb20110801070343/harrypotter/images/thumb/6/62/Pansyinfobox.jpg/250px-Pansyinfobox.jpg", house = slytherin).save()

def fallow(apps, schema_editor):
    House = apps.get_model('hogwarts', 'House')
    Student = apps.get_model('hogwarts', 'Student')
    House.objects.all().delete()
    Student.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('hogwarts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed, fallow)
    ]
