# Generated by Karadi 2020-01-28

from django.db import migrations


def seed(apps, schema_editor):
    Chakras = apps.get_model('chakra_healer', 'Chakras')
    Conditions = apps.get_model('chakra_healer', 'Conditions')
    
    # Chakras
    chakra1 = Chakras(english_name = 'Root', number = 1, sanskrit_name = 'Mulhadhara', color = 'Red',  note = 'A', sound = 'Ay Way', base_frequency = 432, octave_half = 216, octave_qtr = 108, description = 'The Root chakra represents grounding')
    chakra1.save()

    chakra2 = Chakras(english_name = 'Sacral', number = 2, sanskrit_name = 'Swadhistana', color = 'Orange',  note = 'B', sound = 'Ee Me', base_frequency = 480, octave_half = 240, octave_qtr = 120, description = 'The Sacral Chakra represents connection.')
    chakra2.save()

    chakra3 = Chakras(english_name = 'Solar Plexus', number = 3, sanskrit_name = 'Manipura', color = 'Yellow',  note = 'C', sound = 'Uuh Cup', base_frequency = 528, octave_half = 264, octave_qtr = 132, description = 'The Solar Plexus Chakra represents power.')
    chakra3.save()

    chakra4 = Chakras(english_name = 'Heart', number = 4, sanskrit_name = 'Anahata', color = 'Green',  note = 'D', sound = 'Eu You', base_frequency = 600, octave_half = 300, octave_qtr = 150, description = 'The Heart Chakra represents Union.')
    chakra4.save()

    chakra5 = Chakras(english_name = 'Throat', number = 5, sanskrit_name = 'Vishuddha', color = 'Blue',  note = 'E', sound = 'Oh Go', base_frequency = 672, octave_half = 336, octave_qtr = 168, description = 'The Throat Chakra respresents identity and voice.')
    chakra5.save()

    chakra6 = Chakras(english_name = 'Third Eye', number = 6, sanskrit_name = 'Ajna', color = 'Indigo',  note = 'F', sound = 'Ah Mah', base_frequency = 720, octave_half = 360, octave_qtr = 180, description = 'The Third Eye represents timeless vision.')
    chakra6.save()

    chakra7 = Chakras(english_name = 'Crown', number = 7, sanskrit_name = 'Sahasrara', color = 'Violet',  note = 'G', sound = 'I My', base_frequency = 768, octave_half = 384, octave_qtr = 192, description = 'The Crown Chakra represents divine oneness.')
    chakra7.save()
    
    # Conditions

    Conditions(
        condition = 'Attention Deficit', primary_chakra = 6, secondary_chakra = 5, tertiary_chakra = 4
    ).save()

    Conditions(
        condition = 'Alcohol Abuse', primary_chakra = 1, secondary_chakra = 2, tertiary_chakra = 4
    ).save()

    Conditions(
        condition = 'Allergies', primary_chakra = 3, secondary_chakra = 4, tertiary_chakra = 5
    ).save()

    Conditions(
        condition = 'Anxiety', primary_chakra = 1, secondary_chakra = 2, tertiary_chakra = 3
    ).save()

    Conditions(
        condition = 'Back Pain, Lower', primary_chakra = 1, secondary_chakra = 2, tertiary_chakra = 3
    ).save()

    Conditions(
        condition = 'Back Pain, Middle', primary_chakra = 2, secondary_chakra = 3, tertiary_chakra = 4
    ).save()

    Conditions(
        condition = 'Back Pain, Upper', primary_chakra = 3, secondary_chakra = 4, tertiary_chakra = 5
    ).save()

    Conditions(
        condition = 'Eating Disorder', primary_chakra = 1, secondary_chakra = 2, tertiary_chakra = 3
    ).save()

    Conditions(
        condition = 'Cholesterol', primary_chakra = 3, secondary_chakra = 4, tertiary_chakra = 5
    ).save()

    Conditions(
        condition = 'Cold-Flu', primary_chakra = 3, secondary_chakra = 4, tertiary_chakra = 5
    ).save()

    Conditions(
        condition = 'Constipation', primary_chakra = 1, secondary_chakra = 2, tertiary_chakra = 3
    ).save()

    Conditions(
        condition = 'Depression', primary_chakra = 1, secondary_chakra = 2, tertiary_chakra = 4
    ).save()

    Conditions(
        condition = 'Diarrhea', primary_chakra = 1, secondary_chakra = 2, tertiary_chakra = 4
    ).save()

    Conditions(
        condition = 'Edema', primary_chakra = 3, secondary_chakra = 4, tertiary_chakra = 5
    ).save()

    Conditions(
        condition = 'Erectile Dysfunction', primary_chakra = 1, secondary_chakra = 2, tertiary_chakra = 3
    ).save()

    Conditions(
        condition = 'Heartburn', primary_chakra = 2, secondary_chakra = 3, tertiary_chakra = 5
    ).save()

    Conditions(
        condition = 'Hypertension', primary_chakra = 2, secondary_chakra = 3, tertiary_chakra = 4
    ).save()

    Conditions(
        condition = 'Infertility', primary_chakra = 1, secondary_chakra = 2, tertiary_chakra = 4
    ).save()

    Conditions(
        condition = 'Irritable Bowel Disease (IBD)', primary_chakra = 2, secondary_chakra = 3, tertiary_chakra = 4
    ).save()

    Conditions(
        condition = 'Irritable Bowel Syndrom (IBS)', primary_chakra = 1, secondary_chakra = 2, tertiary_chakra = 4
    ).save()

    Conditions(
        condition = 'Joint Pain', primary_chakra = 1, secondary_chakra = 2, tertiary_chakra = 3
    ).save()

    Conditions(
        condition = 'Menstrual Issues', primary_chakra = 1, secondary_chakra = 2, tertiary_chakra = 3
    ).save()

    Conditions(
        condition = 'Headaches', primary_chakra = 6, secondary_chakra = 5, tertiary_chakra = 4
    ).save()

    Conditions(
        condition = 'Sinuses', primary_chakra = 5, secondary_chakra = 4, tertiary_chakra = 3
    ).save()

    Conditions(
        condition = 'Fertility Male', primary_chakra = 1, secondary_chakra = 2, tertiary_chakra = 3
    ).save()

    Conditions(
        condition = 'Fertility Male', primary_chakra = 1, secondary_chakra = 2, tertiary_chakra = 3
    ).save()

    Conditions(
        condition = 'Fertility Female', primary_chakra = 1, secondary_chakra = 2, tertiary_chakra = 5
    ).save()

    Conditions(
        condition = 'Rheumatoid Arthritis', primary_chakra = 1, secondary_chakra = 3, tertiary_chakra = 5
    ).save()

    Conditions(
        condition = 'Skin Inflammation', primary_chakra = 3, secondary_chakra = 3, tertiary_chakra = 5
    ).save()

    Conditions(
        condition = 'Sleep Disorders', primary_chakra = 5, secondary_chakra = 6, tertiary_chakra = 7
    ).save()

    Conditions(
        condition = 'Smoking', primary_chakra = 2, secondary_chakra = 3, tertiary_chakra = 4
    ).save()

    Conditions(
        condition = 'Inflammed Throat', primary_chakra = 4, secondary_chakra = 5, tertiary_chakra = 6
    ).save()

    Conditions(
        condition = 'Overweight', primary_chakra = 1, secondary_chakra = 2, tertiary_chakra = 3
    ).save()

def fallow(apps, schema_editor):
    House = apps.get_model('chakra_healer', 'Chakras')
    Student = apps.get_model('chakra_healer', 'Conditions')
    Chakras.objects.all().delete()
    Conditions.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('chakra_healer', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed, fallow)
    ]
